# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_like_postgres
spring.datasource.username=your_username
spring.datasource.password=your_password

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop 
# you change from create-drop to update later in production 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Optional: log SQL parameters
logging.level.org.hibernate.type.descriptor.sql=TRACE
