# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/community_db
spring.datasource.username=postgres
spring.datasource.password=Munezero

# Hibernate settings
spring.jpa.hibernate.ddl-auto=create-drop   
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Optional: log SQL parameters
logging.level.org.hibernate.type.descriptor.sql=TRACE